env:
  PLUGIN_PROJECT_NAME: Divination.DiscordIntegration
  PLUGIN_REPOSITORY: horoscope-dev/Dalamud.DivinationPluginRepo

### BEGIN TEMPLATE ###

name: CI

on:
  push:
    branches-ignore:
      - 'renovate/**'

  release:
    types:
      - created

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          # Required by GitVersion
          fetch-depth: 0

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri ${{ env.DALAMUD_ZIP_URL }} -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
        env:
          DALAMUD_ZIP_URL: https://goatcorp.github.io/dalamud-distrib/stg/latest.zip

      - name: Prepare Plugin Meta
        run: |
          $json_path = ".\${{ env.PLUGIN_PROJECT_NAME }}\${{ env.PLUGIN_PROJECT_NAME }}.json"
          $json = Get-Content $json_path | ConvertFrom-Json -AsHashtable
          echo "PLUGIN_AUTHOR=Copyright (c) $($json["Author"].Replace(",", "%2c"))" >> $env:GITHUB_ENV
          echo "PLUGIN_DESCRIPTION=$($json["Description"].Replace(",", "%2c"))" >> $env:GITHUB_ENV

      - name: Build Plugin
        run: |
          dotnet build `
            --configuration Release `
            -maxcpucount:1 `
            /p:OutputPath=bin\CIRelease\ `
            /p:Product=Divination `
            /p:Company=Horoscope `
            '/p:Copyright="${{ env.PLUGIN_AUTHOR }}"' `
            '/p:AssemblyTitle="${{ env.PLUGIN_DESCRIPTION }}"'

      - name: Upload Artifact (release)
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PLUGIN_PROJECT_NAME }}
          path: ${{ env.PLUGIN_PROJECT_NAME }}\bin\CIRelease\${{ env.PLUGIN_PROJECT_NAME }}
          if-no-files-found: error

      - name: Upload Artifact (gitversion.json)
        uses: actions/upload-artifact@v3
        with:
          name: gitversion.json
          path: ${{ env.PLUGIN_PROJECT_NAME }}\obj\gitversion.json
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.repository != 'horoscope-dev/Dalamud.Divination.Template' && github.event_name != 'pull_request' && github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Plugin Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.PLUGIN_REPOSITORY }}
          token: ${{ secrets.GH_PAT }}

      - name: Download Artifact (release)
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.PLUGIN_PROJECT_NAME }}
          path: dist/testing/${{ env.PLUGIN_PROJECT_NAME }}

      - name: Download Artifact (gitversion.json)
        uses: actions/download-artifact@v3
        with:
          name: gitversion.json
          path: gitversion

      - name: Read InformationalVersion
        id: version
        run:
          value=$(cat gitversion/gitversion.json | jq .InformationalVersion)
          rm -rf gitversion
          echo "::set-output name=value::$value"

      - name: Prepare commits.json
        run: |
          curl \
            -o dist/testing/${{ env.PLUGIN_PROJECT_NAME }}/commits.json \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            https://api.github.com/repos/${{ github.repository }}/commits

      - name: Prepare event.json
        run: echo '${{ toJSON(github.event) }}' > dist/testing/${{ env.PLUGIN_PROJECT_NAME }}/event.json

      - name: Copy Artifact (stable)
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        run: cp -rf dist/testing/${{ env.PLUGIN_PROJECT_NAME }} dist/stable/${{ env.PLUGIN_PROJECT_NAME }}

      - name: Push to Plugin Repository
        uses: stefanzweifel/git-auto-commit-action@v4
        continue-on-error: true
        with:
          commit_message: 'Deploy ${{ env.PLUGIN_PROJECT_NAME }} ${{ steps.version.outputs.value }}'

  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Format
        run: dotnet format

      - name: Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '🧹 dotnet format'
